// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGF1de5EKcH9Wnnujo66Nzko-k1YmkcrY',
    appId: '1:500258807593:web:6c800a7c67cab4fde8e138',
    messagingSenderId: '500258807593',
    projectId: 'mynotes-code',
    authDomain: 'mynotes-code.firebaseapp.com',
    storageBucket: 'mynotes-code.appspot.com',
    measurementId: 'G-2140NZR1VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZHexF_SuqvEUEt-djGyUN67gGqU_7ew',
    appId: '1:500258807593:android:2246a4190fa5f0a3e8e138',
    messagingSenderId: '500258807593',
    projectId: 'mynotes-code',
    storageBucket: 'mynotes-code.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiid7B3cuqSKvTpERAhH-F6YsRS8gmLyA',
    appId: '1:500258807593:ios:03df8063b3bb87a4e8e138',
    messagingSenderId: '500258807593',
    projectId: 'mynotes-code',
    storageBucket: 'mynotes-code.appspot.com',
    iosClientId:
        '500258807593-1bpue2a7s89pocg7jr9ipcq6fp6k2k22.apps.googleusercontent.com',
    iosBundleId: 'com.mudit.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiid7B3cuqSKvTpERAhH-F6YsRS8gmLyA',
    appId: '1:500258807593:ios:03df8063b3bb87a4e8e138',
    messagingSenderId: '500258807593',
    projectId: 'mynotes-code',
    storageBucket: 'mynotes-code.appspot.com',
    iosClientId:
        '500258807593-1bpue2a7s89pocg7jr9ipcq6fp6k2k22.apps.googleusercontent.com',
    iosBundleId: 'com.mudit.mynotes',
  );
}
